[libkkc] Add workaround for NetBSD 7 gcc-4.8 link command spec changes
With previous version, it's "-lgcc -lc -lgcc" and truncated in
GNU configure generated by libtool.m4
  Workaround ome broken pre-1.5 toolchains
With NetBSD 7 gcc-4.8, it's
 "--as-needed -lgcc_s --no-as-needed -lgcc -lc
  --as-needed -lgcc_s --no-as-needed -lgcc"
Such changes cause build failure with GISCAN
ERROR: can't resolve libraries to shared libraries: gcc

To avoid the issue, truncate such flags after configure.