Update jack to 0.124.1.
Changes not found.

Disable simd option by default, since it breaks compilation for me on
7.99.26/amd64:

./simd.c: In function 'x86_3dnow_add2f':
./simd.c:211:3: error: impossible constraint in 'asm'
   asm volatile (