libmp4v2: No longer require a new GCC version
Use -Wno-return-type to silence compiler errors on clang 4.0.

patch function prototype to fix error in prototype with GCC 4.5.3:
error: prototype for 'Void CMotionVector::setToZero(<type error>)'

Successfully tested clang 4.0, GCC 5.4, GCC 4.5.3.